package eseo.parking.clientws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-03-28T11:35:59.128+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "RequetesBDDService", 
                  wsdlLocation = "file:/C:/Users/trist/IdeaProjects/ProjetHotelJEE-Application/src/eseo/parking/clientws/RequetesBDDPort.wsdl",
                  targetNamespace = "http://servlet.parkingbooking.eseo.fr/") 
public class RequetesBDDService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servlet.parkingbooking.eseo.fr/", "RequetesBDDService");
    public final static QName RequetesBDDPort = new QName("http://servlet.parkingbooking.eseo.fr/", "RequetesBDDPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/trist/IdeaProjects/ProjetHotelJEE-Application/src/eseo/parking/clientws/RequetesBDDPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RequetesBDDService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/trist/IdeaProjects/ProjetHotelJEE-Application/src/eseo/parking/clientws/RequetesBDDPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RequetesBDDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RequetesBDDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RequetesBDDService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RequetesBDDService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RequetesBDDService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RequetesBDDService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RequetesBDDSEI
     */
    @WebEndpoint(name = "RequetesBDDPort")
    public RequetesBDDSEI getRequetesBDDPort() {
        return super.getPort(RequetesBDDPort, RequetesBDDSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RequetesBDDSEI
     */
    @WebEndpoint(name = "RequetesBDDPort")
    public RequetesBDDSEI getRequetesBDDPort(WebServiceFeature... features) {
        return super.getPort(RequetesBDDPort, RequetesBDDSEI.class, features);
    }

}
