
package eseo.parking.clientws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-03-28T11:35:59.027+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class RequetesBDDSEI_RequetesBDDPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servlet.parkingbooking.eseo.fr/", "RequetesBDDService");

    private RequetesBDDSEI_RequetesBDDPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RequetesBDDService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RequetesBDDService ss = new RequetesBDDService(wsdlURL, SERVICE_NAME);
        RequetesBDDSEI port = ss.getRequetesBDDPort();  
        
        {
            /*
        System.out.println("Invoking reserverParking...");
        eseo.parking.clientws.Reservation _reserverParking_arg0 = new eseo.parking.clientws.Reservation();
        port.reserverParking(_reserverParking_arg0);
        */
        }

        {
        System.out.println("Invoking payerParking...");
        //boolean _payerParking__return = port.payerParking(_payerParking_arg0);
        //System.out.println("payerParking.result=" + _payerParking__return);


        }
        {
        System.out.println("Invoking annulerReservationParking...");
        int _annulerReservationParking_arg0 = 0;
        boolean _annulerReservationParking__return = port.annulerReservationParking(_annulerReservationParking_arg0);
        System.out.println("annulerReservationParking.result=" + _annulerReservationParking__return);


        }
        {
        System.out.println("Invoking trouverParking...");
        eseo.parking.clientws.Parking _trouverParking_arg0 = new eseo.parking.clientws.Parking();
        java.util.List<eseo.parking.clientws.Parking> _trouverParking__return = port.trouverParking(_trouverParking_arg0);
        System.out.println("trouverParking.result=" + _trouverParking__return);


        }

        System.exit(0);
    }

}
