package eseo.parking.clientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-03-30T08:15:13.841+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://servlet.parkingbooking.eseo.fr/", name = "RequetesBDDSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface RequetesBDDSEI {

    @WebMethod
    @RequestWrapper(localName = "reserverParking", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.ReserverParking")
    @ResponseWrapper(localName = "reserverParkingResponse", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.ReserverParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverParking(
        @WebParam(name = "arg0", targetNamespace = "")
        eseo.parking.clientws.Reservation arg0
    );

    @WebMethod
    @RequestWrapper(localName = "payerParking", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.PayerParking")
    @ResponseWrapper(localName = "payerParkingResponse", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.PayerParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean payerParking(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "annulerReservationParking", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.AnnulerReservationParking")
    @ResponseWrapper(localName = "annulerReservationParkingResponse", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.AnnulerReservationParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerReservationParking(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverParking", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.TrouverParking")
    @ResponseWrapper(localName = "trouverParkingResponse", targetNamespace = "http://servlet.parkingbooking.eseo.fr/", className = "eseo.parking.clientws.TrouverParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<eseo.parking.clientws.Parking> trouverParking(
        @WebParam(name = "arg0", targetNamespace = "")
        eseo.parking.clientws.Parking arg0
    );
}
