package eseo.hotel.clientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-03-29T10:36:25.337+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://sw.eseo/", name = "GestionHotelsSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface GestionHotelsSEI {

    @WebMethod
    @RequestWrapper(localName = "payerChambre", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.PayerChambre")
    @ResponseWrapper(localName = "payerChambreResponse", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.PayerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String payerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "annulerChambre", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.AnnulerChambre")
    @ResponseWrapper(localName = "annulerChambreResponse", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.AnnulerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "reserverChambre", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.ReserverChambre")
    @ResponseWrapper(localName = "reserverChambreResponse", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.ReserverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        eseo.hotel.clientws.ReservationChambre arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverChambre", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.TrouverChambre")
    @ResponseWrapper(localName = "trouverChambreResponse", targetNamespace = "http://sw.eseo/", className = "eseo.hotel.clientws.TrouverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<eseo.hotel.clientws.Chambre> trouverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        eseo.hotel.clientws.Chambre arg0
    );
}
